### ISSUE TITLE
Static response despite what is being said

### ISSUE THREAD

**Issue by fabianTMC** [gunthercox/chatterbot-voice#13]
I tried running the example script and the only thing I get in response (both when I say something and otherwise) is `Barca still at par than Madrid`.

Any idea on what could be going wrong?

**Comment by gunthercox** [comment]
Hi @fabianTMC, I apologize for the late response (I appear to have lost track of this issue). One reason that you may be getting limited responses is because the example provided with this project doesn't execute any training for the chat bot. As a result, its responses are limited to what it can learn while communicating with the person speaking.

Further information on training is available in the ChatterBot documentation http://chatterbot.readthedocs.io/en/latest/training.html
