### ISSUE TITLE
Running ChatterBot on Linux Server

### ISSUE THREAD

**Issue by openthesource** [gunthercox/chatterbot-voice#9]
Hello All.
I just became fascinated with creating chatbots and extending them not too long ago. I have tried numerous code bases for starting points and this one seems to be the most flexible. Before I go any further I am wondering is it possible and if so how could I develop a chat bot with TTS and Speech Recognition without a display.

**Comment by openthesource** [comment]
Nevermind. This can be closed. I'll just manually apply the xdisplay.

**Comment by openthesource** [comment]
However, fresh install does show errors for checking version. ValueError

**Comment by gunthercox** [comment]
It is definitely possible. I've worked with a number of TTS and Speech Recognition libraries on headless systems.

**Comment by openthesource** [comment]
What have you found to be the greatest obstacle going headless? My goal for this project is to fully automate and decentralize my home. I'm looking to raspberry pi the security system, automate multiple tasks via the lan. 

The chatterbot plays a role as the "assistant". I want it to create "accounts" per user and just really create a full experience.

**Comment by gunthercox** [comment]
I really haven't encountered any obstacles. All of the software that is needed to accomplish this can definitely be run on a Raspberry Pi.

I *have* however encountered some pretty significant obstacles when it comes to trying to do speech recognition on a Raspberry Pi. A huge amount of processing power is needed to convert audio into text and while is is possible to make it work on a Raspberry Pi, it might not be very effective due to the amount of time it takes to produce a response.

**Comment by openthesource** [comment]
Thanks for the reply. You truly have founded some revolutionary code.
